package com.domain;

import java.math.BigDecimal;
import java.util.Date;

public class OrderInfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.id
     *
     * @mbg.generated Thu Jun 23 20:28:48 CST 2022
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.order_no
     *
     * @mbg.generated Thu Jun 23 20:28:48 CST 2022
     */
    private String orderNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.order_amount
     *
     * @mbg.generated Thu Jun 23 20:28:48 CST 2022
     */
    private BigDecimal orderAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.merchant_id
     *
     * @mbg.generated Thu Jun 23 20:28:48 CST 2022
     */
    private Long merchantId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.user_id
     *
     * @mbg.generated Thu Jun 23 20:28:48 CST 2022
     */
    private Long userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.order_freight
     *
     * @mbg.generated Thu Jun 23 20:28:48 CST 2022
     */
    private BigDecimal orderFreight;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.order_status
     *
     * @mbg.generated Thu Jun 23 20:28:48 CST 2022
     */
    private Long orderStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.trans_time
     *
     * @mbg.generated Thu Jun 23 20:28:48 CST 2022
     */
    private Date transTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.pay_status
     *
     * @mbg.generated Thu Jun 23 20:28:48 CST 2022
     */
    private Long payStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.recharge_time
     *
     * @mbg.generated Thu Jun 23 20:28:48 CST 2022
     */
    private Date rechargeTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.pay_amount
     *
     * @mbg.generated Thu Jun 23 20:28:48 CST 2022
     */
    private BigDecimal payAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.pay_discount_amount
     *
     * @mbg.generated Thu Jun 23 20:28:48 CST 2022
     */
    private BigDecimal payDiscountAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.address_id
     *
     * @mbg.generated Thu Jun 23 20:28:48 CST 2022
     */
    private Long addressId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.delivery_type
     *
     * @mbg.generated Thu Jun 23 20:28:48 CST 2022
     */
    private Long deliveryType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.delivery_status
     *
     * @mbg.generated Thu Jun 23 20:28:48 CST 2022
     */
    private Long deliveryStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.delivery_expect_time
     *
     * @mbg.generated Thu Jun 23 20:28:48 CST 2022
     */
    private Date deliveryExpectTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.delivery_complete_time
     *
     * @mbg.generated Thu Jun 23 20:28:48 CST 2022
     */
    private Date deliveryCompleteTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.delivery_amount
     *
     * @mbg.generated Thu Jun 23 20:28:48 CST 2022
     */
    private BigDecimal deliveryAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.coupon_id
     *
     * @mbg.generated Thu Jun 23 20:28:48 CST 2022
     */
    private Long couponId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.remark
     *
     * @mbg.generated Thu Jun 23 20:28:48 CST 2022
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.create_user
     *
     * @mbg.generated Thu Jun 23 20:28:48 CST 2022
     */
    private Long createUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.update_user
     *
     * @mbg.generated Thu Jun 23 20:28:48 CST 2022
     */
    private Long updateUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.create_time
     *
     * @mbg.generated Thu Jun 23 20:28:48 CST 2022
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.update_time
     *
     * @mbg.generated Thu Jun 23 20:28:48 CST 2022
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.delete_flag
     *
     * @mbg.generated Thu Jun 23 20:28:48 CST 2022
     */
    private Byte deleteFlag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.id
     *
     * @return the value of order_info.id
     *
     * @mbg.generated Thu Jun 23 20:28:48 CST 2022
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.id
     *
     * @param id the value for order_info.id
     *
     * @mbg.generated Thu Jun 23 20:28:48 CST 2022
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.order_no
     *
     * @return the value of order_info.order_no
     *
     * @mbg.generated Thu Jun 23 20:28:48 CST 2022
     */
    public String getOrderNo() {
        return orderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.order_no
     *
     * @param orderNo the value for order_info.order_no
     *
     * @mbg.generated Thu Jun 23 20:28:48 CST 2022
     */
    public void setOrderNo(String orderNo) {
        this.orderNo = orderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.order_amount
     *
     * @return the value of order_info.order_amount
     *
     * @mbg.generated Thu Jun 23 20:28:48 CST 2022
     */
    public BigDecimal getOrderAmount() {
        return orderAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.order_amount
     *
     * @param orderAmount the value for order_info.order_amount
     *
     * @mbg.generated Thu Jun 23 20:28:48 CST 2022
     */
    public void setOrderAmount(BigDecimal orderAmount) {
        this.orderAmount = orderAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.merchant_id
     *
     * @return the value of order_info.merchant_id
     *
     * @mbg.generated Thu Jun 23 20:28:48 CST 2022
     */
    public Long getMerchantId() {
        return merchantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.merchant_id
     *
     * @param merchantId the value for order_info.merchant_id
     *
     * @mbg.generated Thu Jun 23 20:28:48 CST 2022
     */
    public void setMerchantId(Long merchantId) {
        this.merchantId = merchantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.user_id
     *
     * @return the value of order_info.user_id
     *
     * @mbg.generated Thu Jun 23 20:28:48 CST 2022
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.user_id
     *
     * @param userId the value for order_info.user_id
     *
     * @mbg.generated Thu Jun 23 20:28:48 CST 2022
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.order_freight
     *
     * @return the value of order_info.order_freight
     *
     * @mbg.generated Thu Jun 23 20:28:48 CST 2022
     */
    public BigDecimal getOrderFreight() {
        return orderFreight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.order_freight
     *
     * @param orderFreight the value for order_info.order_freight
     *
     * @mbg.generated Thu Jun 23 20:28:48 CST 2022
     */
    public void setOrderFreight(BigDecimal orderFreight) {
        this.orderFreight = orderFreight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.order_status
     *
     * @return the value of order_info.order_status
     *
     * @mbg.generated Thu Jun 23 20:28:48 CST 2022
     */
    public Long getOrderStatus() {
        return orderStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.order_status
     *
     * @param orderStatus the value for order_info.order_status
     *
     * @mbg.generated Thu Jun 23 20:28:48 CST 2022
     */
    public void setOrderStatus(Long orderStatus) {
        this.orderStatus = orderStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.trans_time
     *
     * @return the value of order_info.trans_time
     *
     * @mbg.generated Thu Jun 23 20:28:48 CST 2022
     */
    public Date getTransTime() {
        return transTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.trans_time
     *
     * @param transTime the value for order_info.trans_time
     *
     * @mbg.generated Thu Jun 23 20:28:48 CST 2022
     */
    public void setTransTime(Date transTime) {
        this.transTime = transTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.pay_status
     *
     * @return the value of order_info.pay_status
     *
     * @mbg.generated Thu Jun 23 20:28:48 CST 2022
     */
    public Long getPayStatus() {
        return payStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.pay_status
     *
     * @param payStatus the value for order_info.pay_status
     *
     * @mbg.generated Thu Jun 23 20:28:48 CST 2022
     */
    public void setPayStatus(Long payStatus) {
        this.payStatus = payStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.recharge_time
     *
     * @return the value of order_info.recharge_time
     *
     * @mbg.generated Thu Jun 23 20:28:48 CST 2022
     */
    public Date getRechargeTime() {
        return rechargeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.recharge_time
     *
     * @param rechargeTime the value for order_info.recharge_time
     *
     * @mbg.generated Thu Jun 23 20:28:48 CST 2022
     */
    public void setRechargeTime(Date rechargeTime) {
        this.rechargeTime = rechargeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.pay_amount
     *
     * @return the value of order_info.pay_amount
     *
     * @mbg.generated Thu Jun 23 20:28:48 CST 2022
     */
    public BigDecimal getPayAmount() {
        return payAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.pay_amount
     *
     * @param payAmount the value for order_info.pay_amount
     *
     * @mbg.generated Thu Jun 23 20:28:48 CST 2022
     */
    public void setPayAmount(BigDecimal payAmount) {
        this.payAmount = payAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.pay_discount_amount
     *
     * @return the value of order_info.pay_discount_amount
     *
     * @mbg.generated Thu Jun 23 20:28:48 CST 2022
     */
    public BigDecimal getPayDiscountAmount() {
        return payDiscountAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.pay_discount_amount
     *
     * @param payDiscountAmount the value for order_info.pay_discount_amount
     *
     * @mbg.generated Thu Jun 23 20:28:48 CST 2022
     */
    public void setPayDiscountAmount(BigDecimal payDiscountAmount) {
        this.payDiscountAmount = payDiscountAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.address_id
     *
     * @return the value of order_info.address_id
     *
     * @mbg.generated Thu Jun 23 20:28:48 CST 2022
     */
    public Long getAddressId() {
        return addressId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.address_id
     *
     * @param addressId the value for order_info.address_id
     *
     * @mbg.generated Thu Jun 23 20:28:48 CST 2022
     */
    public void setAddressId(Long addressId) {
        this.addressId = addressId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.delivery_type
     *
     * @return the value of order_info.delivery_type
     *
     * @mbg.generated Thu Jun 23 20:28:48 CST 2022
     */
    public Long getDeliveryType() {
        return deliveryType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.delivery_type
     *
     * @param deliveryType the value for order_info.delivery_type
     *
     * @mbg.generated Thu Jun 23 20:28:48 CST 2022
     */
    public void setDeliveryType(Long deliveryType) {
        this.deliveryType = deliveryType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.delivery_status
     *
     * @return the value of order_info.delivery_status
     *
     * @mbg.generated Thu Jun 23 20:28:48 CST 2022
     */
    public Long getDeliveryStatus() {
        return deliveryStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.delivery_status
     *
     * @param deliveryStatus the value for order_info.delivery_status
     *
     * @mbg.generated Thu Jun 23 20:28:48 CST 2022
     */
    public void setDeliveryStatus(Long deliveryStatus) {
        this.deliveryStatus = deliveryStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.delivery_expect_time
     *
     * @return the value of order_info.delivery_expect_time
     *
     * @mbg.generated Thu Jun 23 20:28:48 CST 2022
     */
    public Date getDeliveryExpectTime() {
        return deliveryExpectTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.delivery_expect_time
     *
     * @param deliveryExpectTime the value for order_info.delivery_expect_time
     *
     * @mbg.generated Thu Jun 23 20:28:48 CST 2022
     */
    public void setDeliveryExpectTime(Date deliveryExpectTime) {
        this.deliveryExpectTime = deliveryExpectTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.delivery_complete_time
     *
     * @return the value of order_info.delivery_complete_time
     *
     * @mbg.generated Thu Jun 23 20:28:48 CST 2022
     */
    public Date getDeliveryCompleteTime() {
        return deliveryCompleteTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.delivery_complete_time
     *
     * @param deliveryCompleteTime the value for order_info.delivery_complete_time
     *
     * @mbg.generated Thu Jun 23 20:28:48 CST 2022
     */
    public void setDeliveryCompleteTime(Date deliveryCompleteTime) {
        this.deliveryCompleteTime = deliveryCompleteTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.delivery_amount
     *
     * @return the value of order_info.delivery_amount
     *
     * @mbg.generated Thu Jun 23 20:28:48 CST 2022
     */
    public BigDecimal getDeliveryAmount() {
        return deliveryAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.delivery_amount
     *
     * @param deliveryAmount the value for order_info.delivery_amount
     *
     * @mbg.generated Thu Jun 23 20:28:48 CST 2022
     */
    public void setDeliveryAmount(BigDecimal deliveryAmount) {
        this.deliveryAmount = deliveryAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.coupon_id
     *
     * @return the value of order_info.coupon_id
     *
     * @mbg.generated Thu Jun 23 20:28:48 CST 2022
     */
    public Long getCouponId() {
        return couponId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.coupon_id
     *
     * @param couponId the value for order_info.coupon_id
     *
     * @mbg.generated Thu Jun 23 20:28:48 CST 2022
     */
    public void setCouponId(Long couponId) {
        this.couponId = couponId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.remark
     *
     * @return the value of order_info.remark
     *
     * @mbg.generated Thu Jun 23 20:28:48 CST 2022
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.remark
     *
     * @param remark the value for order_info.remark
     *
     * @mbg.generated Thu Jun 23 20:28:48 CST 2022
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.create_user
     *
     * @return the value of order_info.create_user
     *
     * @mbg.generated Thu Jun 23 20:28:48 CST 2022
     */
    public Long getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.create_user
     *
     * @param createUser the value for order_info.create_user
     *
     * @mbg.generated Thu Jun 23 20:28:48 CST 2022
     */
    public void setCreateUser(Long createUser) {
        this.createUser = createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.update_user
     *
     * @return the value of order_info.update_user
     *
     * @mbg.generated Thu Jun 23 20:28:48 CST 2022
     */
    public Long getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.update_user
     *
     * @param updateUser the value for order_info.update_user
     *
     * @mbg.generated Thu Jun 23 20:28:48 CST 2022
     */
    public void setUpdateUser(Long updateUser) {
        this.updateUser = updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.create_time
     *
     * @return the value of order_info.create_time
     *
     * @mbg.generated Thu Jun 23 20:28:48 CST 2022
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.create_time
     *
     * @param createTime the value for order_info.create_time
     *
     * @mbg.generated Thu Jun 23 20:28:48 CST 2022
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.update_time
     *
     * @return the value of order_info.update_time
     *
     * @mbg.generated Thu Jun 23 20:28:48 CST 2022
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.update_time
     *
     * @param updateTime the value for order_info.update_time
     *
     * @mbg.generated Thu Jun 23 20:28:48 CST 2022
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.delete_flag
     *
     * @return the value of order_info.delete_flag
     *
     * @mbg.generated Thu Jun 23 20:28:48 CST 2022
     */
    public Byte getDeleteFlag() {
        return deleteFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.delete_flag
     *
     * @param deleteFlag the value for order_info.delete_flag
     *
     * @mbg.generated Thu Jun 23 20:28:48 CST 2022
     */
    public void setDeleteFlag(Byte deleteFlag) {
        this.deleteFlag = deleteFlag;
    }
}